# Generated by Django 5.0.2 on 2025-12-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_plant_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='plants/'),
        ),
    ]
